# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfswitch < Formula
  desc "The tfswitch command lets you switch between terraform versions."
  homepage "https://versus.github.io/terraform-switcher"
  version "0.21.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/versus/terraform-switcher/releases/download/0.21.1/terraform-switcher_0.21.1_darwin_amd64.tar.gz"
    sha256 "4104661731374fd2ac3e1f5e5f2006c9fed9e557a93e54c49346a2bb0aac8ebb"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/versus/terraform-switcher/releases/download/0.21.1/terraform-switcher_0.21.1_linux_amd64.tar.gz"
    sha256 "39996451a48818377fa661b3f35c6365a4d6053f04704ba49eaa202a7e04cc16"
  end

  conflicts_with "terraform"

  def install
    bin.install "tfswitch"
  end

  def caveats; <<~EOS
    Type 'tfswitch' on your command line and choose the terraform version that you want from the dropdown. This command currently only works on MacOs and Linux
  EOS
  end

  test do
    system "#{bin}/tfswitch --version"
  end
end
