# This file was generated by GoReleaser. DO NOT EDIT.
class Tfswitch < Formula
  desc "The tfswitch command lets you switch between terraform versions."
  homepage "https://versus.github.io/terraform-switcher"
  version "0.9.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/versus/terraform-switcher/releases/download/0.9.9/terraform-switcher_0.9.9_darwin_amd64.tar.gz"
    sha256 "c6c7096c1d7a357c64d1ccf99cddfb66748a0af294ff50dd65de576684283590"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/versus/terraform-switcher/releases/download/0.9.9/terraform-switcher_0.9.9_linux_amd64.tar.gz"
      sha256 "b0f034666d3a25a08821231ba2321fd860a57d716ac892860b60f184cd76a083"
    end
  end
  
  conflicts_with "terraform"

  def install
    bin.install "tfswitch"
  end

  def caveats; <<~EOS
    Type 'tfswitch' on your command line and choose the terraform version that you want from the dropdown. This command currently only works on MacOs and Linux
  EOS
  end

  test do
    system "#{bin}/tfswitch --version"
  end
end
